package fi.javaguru.akismet.mb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AkismetMBMessage service. Represents a row in the &quot;Akismet_AkismetMBMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.javaguru.akismet.mb.model.impl.AkismetMBMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.javaguru.akismet.mb.model.impl.AkismetMBMessageImpl}.
 * </p>
 *
 * @author Mika Koivisto
 * @see AkismetMBMessage
 * @see fi.javaguru.akismet.mb.model.impl.AkismetMBMessageImpl
 * @see fi.javaguru.akismet.mb.model.impl.AkismetMBMessageModelImpl
 * @generated
 */
public interface AkismetMBMessageModel extends BaseModel<AkismetMBMessage> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a akismet m b message model instance should use the {@link AkismetMBMessage} interface instead.
     */

    /**
     * Returns the primary key of this akismet m b message.
     *
     * @return the primary key of this akismet m b message
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this akismet m b message.
     *
     * @param primaryKey the primary key of this akismet m b message
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the akismet m b message ID of this akismet m b message.
     *
     * @return the akismet m b message ID of this akismet m b message
     */
    public long getAkismetMBMessageId();

    /**
     * Sets the akismet m b message ID of this akismet m b message.
     *
     * @param akismetMBMessageId the akismet m b message ID of this akismet m b message
     */
    public void setAkismetMBMessageId(long akismetMBMessageId);

    /**
     * Returns the company ID of this akismet m b message.
     *
     * @return the company ID of this akismet m b message
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this akismet m b message.
     *
     * @param companyId the company ID of this akismet m b message
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this akismet m b message.
     *
     * @return the group ID of this akismet m b message
     */
    public long getGroupId();

    /**
     * Sets the group ID of this akismet m b message.
     *
     * @param groupId the group ID of this akismet m b message
     */
    public void setGroupId(long groupId);

    /**
     * Returns the create date of this akismet m b message.
     *
     * @return the create date of this akismet m b message
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this akismet m b message.
     *
     * @param createDate the create date of this akismet m b message
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this akismet m b message.
     *
     * @return the modified date of this akismet m b message
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this akismet m b message.
     *
     * @param modifiedDate the modified date of this akismet m b message
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the mb message ID of this akismet m b message.
     *
     * @return the mb message ID of this akismet m b message
     */
    public long getMbMessageId();

    /**
     * Sets the mb message ID of this akismet m b message.
     *
     * @param mbMessageId the mb message ID of this akismet m b message
     */
    public void setMbMessageId(long mbMessageId);

    /**
     * Returns the spam of this akismet m b message.
     *
     * @return the spam of this akismet m b message
     */
    public boolean getSpam();

    /**
     * Returns <code>true</code> if this akismet m b message is spam.
     *
     * @return <code>true</code> if this akismet m b message is spam; <code>false</code> otherwise
     */
    public boolean isSpam();

    /**
     * Sets whether this akismet m b message is spam.
     *
     * @param spam the spam of this akismet m b message
     */
    public void setSpam(boolean spam);

    /**
     * Returns the author of this akismet m b message.
     *
     * @return the author of this akismet m b message
     */
    @AutoEscape
    public String getAuthor();

    /**
     * Sets the author of this akismet m b message.
     *
     * @param author the author of this akismet m b message
     */
    public void setAuthor(String author);

    /**
     * Returns the author email of this akismet m b message.
     *
     * @return the author email of this akismet m b message
     */
    @AutoEscape
    public String getAuthorEmail();

    /**
     * Sets the author email of this akismet m b message.
     *
     * @param authorEmail the author email of this akismet m b message
     */
    public void setAuthorEmail(String authorEmail);

    /**
     * Returns the author url of this akismet m b message.
     *
     * @return the author url of this akismet m b message
     */
    @AutoEscape
    public String getAuthorUrl();

    /**
     * Sets the author url of this akismet m b message.
     *
     * @param authorUrl the author url of this akismet m b message
     */
    public void setAuthorUrl(String authorUrl);

    /**
     * Returns the content of this akismet m b message.
     *
     * @return the content of this akismet m b message
     */
    @AutoEscape
    public String getContent();

    /**
     * Sets the content of this akismet m b message.
     *
     * @param content the content of this akismet m b message
     */
    public void setContent(String content);

    /**
     * Returns the permalink of this akismet m b message.
     *
     * @return the permalink of this akismet m b message
     */
    @AutoEscape
    public String getPermalink();

    /**
     * Sets the permalink of this akismet m b message.
     *
     * @param permalink the permalink of this akismet m b message
     */
    public void setPermalink(String permalink);

    /**
     * Returns the referrer of this akismet m b message.
     *
     * @return the referrer of this akismet m b message
     */
    @AutoEscape
    public String getReferrer();

    /**
     * Sets the referrer of this akismet m b message.
     *
     * @param referrer the referrer of this akismet m b message
     */
    public void setReferrer(String referrer);

    /**
     * Returns the type of this akismet m b message.
     *
     * @return the type of this akismet m b message
     */
    @AutoEscape
    public String getType();

    /**
     * Sets the type of this akismet m b message.
     *
     * @param type the type of this akismet m b message
     */
    public void setType(String type);

    /**
     * Returns the user agent of this akismet m b message.
     *
     * @return the user agent of this akismet m b message
     */
    @AutoEscape
    public String getUserAgent();

    /**
     * Sets the user agent of this akismet m b message.
     *
     * @param userAgent the user agent of this akismet m b message
     */
    public void setUserAgent(String userAgent);

    /**
     * Returns the user ID of this akismet m b message.
     *
     * @return the user ID of this akismet m b message
     */
    public long getUserId();

    /**
     * Sets the user ID of this akismet m b message.
     *
     * @param userId the user ID of this akismet m b message
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this akismet m b message.
     *
     * @return the user uuid of this akismet m b message
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this akismet m b message.
     *
     * @param userUuid the user uuid of this akismet m b message
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the user ip of this akismet m b message.
     *
     * @return the user ip of this akismet m b message
     */
    @AutoEscape
    public String getUserIp();

    /**
     * Sets the user ip of this akismet m b message.
     *
     * @param userIp the user ip of this akismet m b message
     */
    public void setUserIp(String userIp);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(AkismetMBMessage akismetMBMessage);

    public int hashCode();

    public CacheModel<AkismetMBMessage> toCacheModel();

    public AkismetMBMessage toEscapedModel();

    public String toString();

    public String toXmlString();
}
